minio:
  enabled: false
  replicas: 1
  drivesPerNode: 2
  rootUser: loki
  rootPassword: lokiloki

loki:
  image:
    repository: grafana/loki
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
  auth_enabled: false
  storage:
    bucketNames:
      chunks: loki 
      ruler: loki
      admin: loki
    type: s3
    s3:
      accessKeyId: loki
      endpoint: http://minio.minio.svc.cluster.local:9000
      insecure: true
      s3ForcePathStyle: true
      secretAccessKey: lokiloki

write:
  # -- Number of replicas for the write
  replicas: 1
read:
  # -- Number of replicas for the read
  replicas: 1
backend:
  # -- Number of replicas for the backend
  replicas: 1
